from __future__ import annotations

import json
import logging
import math
from pathlib import Path
from typing import Any

from sklearn.ensemble import GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score, accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from ..processors.feature_extractor import (
    INDICATION_GROUPS, MECHANISM_GROUPS,
    extract_features, label_for_training, characterize,
)
from ..storage.repository import fetch_all, save_model_run


def _build_historical_lessons(fmt_classes: list[str]) -> list[dict[str, Any]]:
    """Thin shim — defers to analytics to avoid circular imports at module load."""
    try:
        from ..analysis.analytics import cross_modality_lessons
        return cross_modality_lessons(fmt_classes)
    except Exception:
        return []

logger = logging.getLogger(__name__)

# Sources generated by simulation — excluded from ML training by default.
# They are still used by the RL cohort simulator and the 30-year analysis.
SYNTHETIC_SOURCES = frozenset({"historical_cohort", "hist30_cohort"})

# Terminal-state sources record the FINAL stage a drug reached, not where it
# currently stands.  For these, we expand each record into one training sample
# per clinical stage the drug passed through (trajectory expansion) so the
# model learns "at Phase N, does this drug advance?" rather than the trivial
# "Phase 4 = approved, Phase 1 = discontinued."
TERMINAL_STATE_SOURCES = frozenset({"chembl", "fda_approvals", "ema_medicines"})

# Ordered clinical stages used during trajectory expansion
_TRAJ_STAGES = ["phase1", "phase2", "phase3"]
_STAGE_ORDER: dict[str, float] = {
    "preclinical":   0.0,
    "phase1":        1.0,
    "phase2":        2.0,
    "phase3":        3.0,
    "nda_submitted": 3.5,
    "approved":      4.0,
}


def _expand_trajectory(row: dict) -> list[tuple[dict, int]]:
    """
    For a terminal-state record expand it into per-stage decision samples.

    A drug that reached Phase 3 and stopped:
      phase1 row → label 1  (advanced to Phase 2)
      phase2 row → label 1  (advanced to Phase 3)
      phase3 row → label 0  (stopped here)

    An approved drug:
      phase1 row → label 1
      phase2 row → label 1
      phase3 row → label 1

    A drug discontinued at Phase 1:
      phase1 row → label 0
    """
    outcome = row.get("outcome", "unknown")
    terminal_stage = row.get("clinical_stage", "unknown")
    terminal_order = _STAGE_ORDER.get(terminal_stage, -1.0)

    if terminal_order < 0:
        return []

    # Determine the terminal label at the stopping stage
    if outcome == "approved":
        terminal_label = 1
    elif "discontinued" in outcome:
        terminal_label = 0
    else:
        return []   # ongoing / unknown — skip

    samples: list[tuple[dict, int]] = []
    for stage in _TRAJ_STAGES:
        s_order = _STAGE_ORDER[stage]
        if s_order < terminal_order:
            # Drug advanced past this stage → GO
            samples.append(({**row, "clinical_stage": stage}, 1))
        elif abs(s_order - terminal_order) < 0.1:
            # This is the terminal stage
            samples.append(({**row, "clinical_stage": stage}, terminal_label))
        # stages beyond terminal_order → don't generate (drug never got there)

    return samples


# ── Feature matrix builder ───────────────────────────────────────────────────

def build_feature_matrix(db_path: Path | None = None, real_only: bool = True) -> tuple[list[list[float]], list[int], list[str]]:
    """
    Returns (X, y, feature_names) for supervised learning.

    For terminal-state sources (ChEMBL, FDA, EMA) each record is expanded into
    one training sample per clinical stage the drug passed through.  This prevents
    stage_weight from trivially encoding the label (phase=4 ≡ approved).

    For decision-point sources (ClinicalTrials, VC portfolio, etc.) records are
    used as-is — they already represent a drug at a specific stage with an
    independent outcome (TERMINATED vs COMPLETED).
    """
    kwargs = {"db_path": db_path} if db_path else {}
    rows = fetch_all(**kwargs)

    if real_only:
        rows = [r for r in rows if r.get("source") not in SYNTHETIC_SOURCES]
        logger.info("build_feature_matrix: using %d real-world records (synthetic excluded)", len(rows))

    X: list[list[float]] = []
    y: list[int] = []
    sample_features: dict[str, float] | None = None

    for row in rows:
        source = row.get("source", "")
        if source in TERMINAL_STATE_SOURCES:
            # Expand terminal record into per-stage decision samples
            for expanded_row, label in _expand_trajectory(row):
                feats = extract_features(expanded_row)
                if sample_features is None:
                    sample_features = feats
                X.append(list(feats.values()))
                y.append(label)
        else:
            # Decision-point record — use as-is
            label = label_for_training(row)
            if label is None:
                continue
            feats = extract_features(row)
            if sample_features is None:
                sample_features = feats
            X.append(list(feats.values()))
            y.append(label)

    feature_names = list(sample_features.keys()) if sample_features else []
    logger.info("build_feature_matrix: %d training samples after trajectory expansion", len(X))
    return X, y, feature_names


# ── Bayesian prior calibration ────────────────────────────────────────────────

def calibrate_priors(db_path: Path | None = None) -> dict[str, float]:
    """
    Compute empirical success rates per (indication, stage) from DB.
    Returns a dict keyed by "indication:stage" → P(success).
    """
    kwargs = {"db_path": db_path} if db_path else {}
    rows = fetch_all(**kwargs)

    counts: dict[str, dict[str, int]] = {}
    for row in rows:
        key = f"{row['indication']}:{row['clinical_stage']}"
        if key not in counts:
            counts[key] = {"success": 0, "fail": 0}
        outcome = row.get("outcome", "unknown")
        if outcome in ("approved", "ongoing"):
            counts[key]["success"] += 1
        elif "discontinued" in outcome:
            counts[key]["fail"] += 1

    priors: dict[str, float] = {}
    for key, c in counts.items():
        total = c["success"] + c["fail"]
        if total >= 3:   # minimum sample requirement
            # Laplace smoothing
            priors[key] = (c["success"] + 1) / (total + 2)
    return priors


# ── Supervised success predictor ──────────────────────────────────────────────

class SuccessPredictor:
    """
    Predicts P(success) for a bioventure project given its features.
    Ensemble of logistic regression + gradient boosting.
    Falls back to feature-derived prior if insufficient training data.
    """

    MIN_SAMPLES = 20

    def __init__(self) -> None:
        self.scaler = StandardScaler()
        self.lr = LogisticRegression(max_iter=500, C=0.5, class_weight="balanced")
        self.gb = GradientBoostingClassifier(n_estimators=80, max_depth=3, learning_rate=0.05)
        self.feature_names: list[str] = []
        self.is_fitted = False
        self.priors: dict[str, float] = {}

    def train(self, db_path: Path | None = None) -> dict[str, Any]:
        kwargs = {"db_path": db_path} if db_path else {}
        # Train exclusively on real-world data (no synthetic simulation records)
        X, y, feat_names = build_feature_matrix(real_only=True, **kwargs)
        self.feature_names = feat_names
        self.priors = calibrate_priors(**kwargs)

        if len(X) < self.MIN_SAMPLES:
            logger.warning(
                "Only %d labelled samples — skipping supervised training, "
                "using prior-based prediction only.", len(X)
            )
            self.is_fitted = False
            return {"status": "skipped_insufficient_data", "n": len(X)}

        X_train, X_test, y_train, y_test = train_test_split(
            X, y, test_size=0.2, random_state=42, stratify=y
        )

        X_train_s = self.scaler.fit_transform(X_train)
        X_test_s = self.scaler.transform(X_test)

        self.lr.fit(X_train_s, y_train)
        self.gb.fit(X_train_s, y_train)

        # Ensemble: average probabilities
        p_lr = self.lr.predict_proba(X_test_s)[:, 1]
        p_gb = self.gb.predict_proba(X_test_s)[:, 1]
        p_ens = (p_lr + p_gb) / 2

        auc = roc_auc_score(y_test, p_ens)
        acc = accuracy_score(y_test, (p_ens >= 0.5).astype(int))
        self.is_fitted = True

        logger.info("SuccessPredictor trained: AUC=%.3f, ACC=%.3f, n=%d", auc, acc, len(X))
        save_model_run(
            "SuccessPredictor_ensemble", auc, acc,
            len(X_train), len(X_test),
            {"lr_C": 0.5, "gb_n": 80},
            **kwargs,
        )
        return {"auc": round(auc, 4), "accuracy": round(acc, 4), "n_train": len(X_train), "n_test": len(X_test)}

    def predict(self, row: dict[str, Any]) -> float:
        """
        Returns P(success) ∈ [0, 1] for a drug program described by `row`.

        Post-model calibration adjustments applied after the ensemble score:
        - validated_target (+0.08):  target has ≥1 approved drug — biology de-risked
        - unvalidated_target (−0.06): novel target, higher biological risk
        - has_completion_signal (+0.10): text indicates positive data / approval
        - has_failure_signal (−0.15): text indicates termination / failed primary

        These nudges reflect known industry facts that are sparse in training text
        but reliably signal program quality.
        """
        feats = extract_features(row)
        feat_values = [feats[k] for k in self.feature_names] if self.feature_names else list(feats.values())
        prior_key = f"{row.get('indication', 'unknown')}:{row.get('clinical_stage', 'unknown')}"
        fallback = self.priors.get(prior_key, feats.get("prior_probability", 0.35))

        if not self.is_fitted or not self.feature_names:
            return fallback

        feat_2d = self.scaler.transform([feat_values])
        p_lr = self.lr.predict_proba(feat_2d)[0, 1]
        p_gb = self.gb.predict_proba(feat_2d)[0, 1]
        p = (p_lr + p_gb) / 2

        # Post-model calibration: domain-knowledge adjustments applied after ensemble
        p += feats.get("validated_target", 0.0)   * +0.25
        p += feats.get("unvalidated_target", 0.0) * -0.08
        p += feats.get("has_completion_signal", 0.0) * +0.15
        p += feats.get("has_failure_signal", 0.0)    * -0.18

        # Technology fit calibration
        # Clear-cut tech-indication match (e.g. CRISPR + rare disease): bonus
        # Good but not clear-cut (score 0.5-0.8): small nudge
        # Poor fit (score < 0.4): mild penalty for misaligned platform
        tech_fit = feats.get("tech_fit_score", 0.35)
        if feats.get("tech_is_clearcut", 0.0) == 1.0:
            p += 0.12
        elif tech_fit >= 0.7:
            p += 0.05
        elif tech_fit < 0.35 and feats.get("is_bleeding_edge", 0.0) == 1.0:
            p -= 0.05   # bleeding-edge in a poorly-matched indication = extra risk

        return round(max(0.01, min(0.99, p)), 4)

    def explain(self, row: dict[str, Any]) -> dict[str, Any]:
        """
        Full decision report for a single bioventure program.

        Returns:
        {
          "p_success":      float — P(success) 0–1
          "verdict":        str   — GO / NO-GO
          "score_pct":      str   — e.g. '42.3%'
          "technology":     dict  — from characterize()
          "calibration":    dict  — which nudges were applied and by how much
        }
        """
        p = self.predict(row)
        char = characterize(row)
        feats = extract_features(row)

        calibration: list[dict[str, Any]] = []
        if feats.get("validated_target"):
            calibration.append({"factor": "Validated molecular target", "adjustment": "+0.25"})
        if feats.get("unvalidated_target"):
            calibration.append({"factor": "Unvalidated molecular target", "adjustment": "-0.08"})
        if feats.get("has_completion_signal"):
            calibration.append({"factor": "Positive outcome signal in text", "adjustment": "+0.15"})
        if feats.get("has_failure_signal"):
            calibration.append({"factor": "Failure / termination signal in text", "adjustment": "-0.18"})
        if feats.get("tech_is_clearcut") == 1.0:
            calibration.append({"factor": "Clear-cut tech-indication fit", "adjustment": "+0.12"})
        elif feats.get("tech_fit_score", 0) >= 0.7:
            calibration.append({"factor": "Good tech-indication fit", "adjustment": "+0.05"})
        elif feats.get("tech_fit_score", 0) < 0.35 and feats.get("is_bleeding_edge") == 1.0:
            calibration.append({"factor": "Bleeding-edge tech in mismatched indication", "adjustment": "-0.05"})

        return {
            "p_success":   p,
            "verdict":     "GO" if p >= 0.5 else "NO-GO",
            "score_pct":   f"{p:.1%}",
            "technology": {
                "platform":         char["tech_labels"],
                "is_bleeding_edge": char["is_bleeding_edge"],
                "fit_score":        char["tech_fit"]["score"],
                "is_clearcut":      char["tech_fit"]["is_clearcut"],
                "fit_rationale":    char["tech_fit"]["rationale"],
                "formats":          char["formats"]["labels"],
                "format_notes":     char["formats"]["notes"],
            },
            "frontier": {
                "modality":   char["frontier"]["modality"],
                "in_use":     [{"tech": e["tech"], "status": e["status"],
                                "pursuit_level": e["pursuit_level"], "note": e["note"]}
                               for e in char["frontier"]["in_use"]],
                "not_using":  [{"tech": e["tech"], "status": e["status"],
                                "pursuit_level": e["pursuit_level"]}
                               for e in char["frontier"]["not_using"]],
            },
            "biology": {
                "target_status":    char["target_status"],
                "detected_targets": char["detected_targets"],
            },
            "signals":        char["signals"],
            "safety_profile": char["safety_profile"],
            "historical_lessons": _build_historical_lessons(char["formats"]["classes"]),
            "calibration": calibration,
            "summary":     char["verdict"],
        }

    def feature_importance(self) -> list[tuple[str, float]]:
        if not self.is_fitted:
            return []
        importances = self.gb.feature_importances_
        pairs = list(zip(self.feature_names, importances))
        return sorted(pairs, key=lambda x: -x[1])

    def modality_trends(
        self,
        top_n: int = 10,
        min_records: int = 3,
        recent_from: int = 2022,
    ) -> dict:
        """
        Portfolio-level modality trend intelligence.

        Returns:
          hot_formats       — highest volume × recency heat score
          emerging_formats  — fastest-rising formats from a low base ("next new thing")
          by_modality       — per-category breakdown ranked by heat score
          params            — windows used for scoring

        Usage:
          model = SuccessPredictor(); model.train()
          trends = model.modality_trends()
          for fmt in trends["hot_formats"]:
              print(fmt["format"], fmt["heat_score"])
        """
        from ..analysis.analytics import modality_trend_report
        return modality_trend_report(
            db_path=self.db_path if hasattr(self, "db_path") else None,
            top_n=top_n,
            min_records=min_records,
            recent_from=recent_from,
        )
